course_access_groups/apps.py, course_access_groups/monkeypatch.py, mocks/__init__.py, mocks/xmodule/__init__.py, mocks/xmodule/course_module.py, pytest.ini, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, setup.py, tox.ini
Inspired by the [edX Zoom XBlock](https://github.com/edx/edx-zoom/blob/37c323ae93265937bf60abb92657318efeec96c5/edx_zoom/utils.py#L6-L11).
<kbd>![image](https://user-images.githubusercontent.com/645156/72282683-369f9b00-364e-11ea-9d96-35106262e8a5.png)</kbd>
=> Add the studio field

tests/test_api.py
Refactoring and docs for the `test_api.py`. No functionality change.
=> Cleanup, simplify and add docs for test_api.py

course_access_groups/apps.py, mocks/openedx/core/djangoapps/plugins/__init__.py, mocks/openedx/core/djangoapps/plugins/constants.py, tests/test_app_config.py
Make URLs discoverable by Open edX using the "Hawthorn" plugins system.
=> Plugin and URL configs for Open edX

course_access_groups/acl_backends.py, course_access_groups/permissions.py, course_access_groups/views.py, mocks/openedx/core/lib/__init__.py, mocks/openedx/core/lib/api/__init__.py, mocks/openedx/core/lib/api/authentication/__init__.py, test_utils/__init__.py, test_utils/factories.py, tests/test_api.py, tests/test_api_permissions.py, tests/test_security.py
=> CommonAuthMixin for views

course_access_groups/acl_backends.py, course_access_groups/permissions.py, test_utils/__init__.py, tests/conftest.py, tests/test_permissions.py
=> is_active_staff_or_superuser helper

.travis.yml, tox.ini
To catch common `admin.py` errors if any.
=> Check for common Django issues

course_access_groups/acl_backends.py
=> Document is_organization_staff: Checking for `user.is_active` again. Better to be safe than sorry

course_access_groups/admin.py, course_access_groups/models.py, mocks/openedx/core/djangoapps/content/course_overviews/models.py, tests/test_admin.py, tests/test_models.py
=> Models Admins for Course Access Groups

course_access_groups/models.py, course_access_groups/validators.py, tests/test_models.py
=> Validate the MembershipRule.domain field

tests/test_api.py
=> Tests for DELETE actions on the API

tests/test_api_permissions.py
=> Fix naming and docs in test_api_permissions.py

docs/rest_api.rst
Following up on #34 I'm opting for more succinct docs to make it easy to maintain the docs in the future.
=> Docs for membership rules

docs/rest_api.rst
Following up on #34 I'm opting for more succinct docs to make it easy to maintain the docs in the future.
=> Docs for User Membership in Course Access Groups

docs/getting_started.rst
`course.load` is properly handled by the platform and is good for CAG out of the box.
=> fix recommended configs after testing on devstack

README.rst, docs/engineering_design.rst
This is the most basic engieering docs I could think of. 
I have no plans to extend it in the future, unless we get some repeated questions that justifies spending time on it.
After it's merged these docs would make it into: https://course-access-groups.readthedocs.io/
=> Added some engineering design docs.

docs/getting_started.rst
What worked on Matej's machine.
=> Add devstack installation steps

.travis.yml, course_access_groups/serializers.py, manage.py, mocks/openedx/core/djangoapps/content/course_overviews/models.py, setup.py, test_utils/__init__.py, test_utils/factories.py, tests/test_api.py, tests/test_models.py, tests/test_permissions.py, tox.ini
**Description:** Adds flake8 check to tox config and enables it on TravisCI
**JIRA:** https://appsembler.atlassian.net/browse/OT-276
Closes https://github.com/appsembler/course-access-groups/issues/9
=> Tox flake8

course_access_groups/urls.py, course_access_groups/views.py, docs/rest_api.rst
I merged incomplete docs in #47 and view name was inconsistently plural.
=> User API: Fixed stale docs and unified view name

.travis.yml
Set this up the same as Figures. Internal docs for how to trigger a PyPI release: https://appsembler.atlassian.net/wiki/spaces/ED/pages/41550165/New+PyPI+release
Close #2
=> configure PyPI uploads via TravisCI

CHANGELOG.rst
Change log entry and some cleanup. I always forget that.
=> Change log vor v0.5.1

CHANGELOG.rst, docs/rest_api.rst, tests/test_api.py
=> Tests and docs fixes for membership rule PATCH

docs/rest_api.rst
More on RED-2387.
It's amazing how ReadTheDoc updates docs automatically without requiring an integration!
=> style doc fix for MembershipRule API

.github/workflows/ci.yml, course_access_groups/models.py, course_access_groups/permissions.py, course_access_groups/serializers.py, course_access_groups/views.py, requirements/base.in, requirements/base.txt, requirements/doc.txt, requirements/test.txt, test_settings.py, test_utils/factories.py, tests/test_acl_backend.py, tests/test_api.py, tests/test_models.py, tests/test_permissions.py, tox.ini
**Description:** Describe in a couple of sentences what this PR adds
**JIRA:** Link to JIRA ticket
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Use the new UserOrganizationMapping and TahoeSiteUUID

course_access_groups/__init__.py, course_access_groups/signals.py, tests/test_signals.py
=>  fix ValueError for inactive users' REGISTER_USER singal

course_access_groups/models.py, course_access_groups/permissions.py, course_access_groups/serializers.py, course_access_groups/views.py, requirements/base.in, requirements/base.txt, requirements/doc.txt, requirements/test.txt, tests/test_api.py, tests/test_permissions.py
**Description:** Organization-Site Link using TahoeSite
related to: https://github.com/appsembler/tahoe-sites/pull/8
**JIRA:**
https://appsembler.atlassian.net/browse/RED-2726
https://appsembler.atlassian.net/browse/RED-2705
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Organization-Site Link using TahoeSite

course_access_groups/permissions.py, requirements/base.in, requirements/base.txt, requirements/doc.txt, requirements/test.txt, tests/test_permissions.py
**Description:** Move get_current_organization to this package
**JIRA:** https://appsembler.atlassian.net/browse/RED-2706
**Dependencies:** https://github.com/appsembler/tahoe-sites/pull/20
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Move get_current_organization to tahoe_sites package

course_access_groups/models.py, course_access_groups/views.py, requirements/base.in, requirements/base.txt, requirements/doc.txt, requirements/test.txt
**Description:** Use tahoe-sites v0.1.2 (mainly use `get_organization_for_user` instead of `get_organizations_for_user`)
**JIRA:** 
**Dependencies:** 
**Merge deadline:** 
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Use tahoe-sites v0.1.2

course_access_groups/permissions.py, requirements/base.in, requirements/base.txt, requirements/doc.txt, requirements/test.txt, tests/test_permissions.py
**Description:** 
* Use tahoe_sites.api.get_organization_for_user
* Fix is_organization_staff multi-organizations issue
**JIRA:** 
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Use tahoe_sites.api.get_organization_for_user

requirements/base.txt, requirements/doc.txt, requirements/test.txt
**Description:** Use `tahoe-site==1.2.0` . No changes are needed in the code. This is just to use the latest version
**JIRA:** Link to JIRA ticket
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Use tahoe-site v1.2.0

CHANGELOG.rst, course_access_groups/__init__.py
**Description:** Bump version to v0.6.0
**JIRA:** Link to JIRA ticket
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Bump version to v0.6.0
